spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # ???? spring.io?? doc?? ??? ??????.
  # jpa??
  jpa:
    hibernate: # hibernate ?? ??
      # ?????? ?? ??? ???? ? ???, ?? ?? entity ??? ?? ?? ??? ?? ??
      # if exists drop table ??? ?? ?????? ?? ??.
      ddl-auto: create
    properties: # property ?? ??
      hibernate: # hibernate property ??
        format_sql: true

# ?? ?? ??
logging:
  level:
    # hibernate ? ??? ?? ??? debug??? ??
    # jpa hibernate? ???? sql? ??? ??? ???? ?? ??
    org.hibernate.SQL: debug
    org.hibernate.type: trace # ?? ???? ????? ???? ??
